### ISSUE TITLE
Resource amount

### ISSUE THREAD

**Issue by GuiltyNeko** [Pandemoneus/Resource-Labels#1]
It'd be appreciated if you could also generate the label name with the amount of the resources in the patch. Not down to the last ore piece, of course, but abbreviated. K for thousand, M for million, so on. This would make it much easier to tell how much ore has been mined from a patch.

**Comment by Pandemoneus** [comment]
I thought about adding them when I made the mod, but I decided against it because  
* it adds more clutter
* you can see the resource count when you hover over the ore patch.
However, I can add it as optional element. It will not be enabled by default.

**Comment by Pandemoneus** [comment]
Added with commit https://github.com/Pandemoneus/Resource-Labels/commit/4af778a947e6e724d51e8e0446d0e8b96847af4b , uploading to the Factorio mod portal in a few minutes.
