### ISSUE TITLE
Angel's Gardens

### ISSUE THREAD

**Issue by StephanSteinert** [Pandemoneus/Resource-Labels#11]
Hi,

can you please add the Angel's Gardens?

Problem: They are trees not ores.

Would be very nice as they are hard to find.
The definitions are in Angel's Bioprocessing\prototypes\buildings\gardens.lua

addItem ("temptemperate-garden", "Temperate Garden", "temperate-garden")
addItem ("desert-garden", "Desert Garden", "desert-garden")
addItem ("swamp-garden", "Swamp Garden", "swamp-garden")

**Comment by Pandemoneus** [comment]
Sorry, but my mod does not handle entities that are not resources at the moment, as you said. I will consider this for a seperate mod where you can define which entities you want to have marked.
