### ISSUE TITLE
Error in deep core mining support

### ISSUE THREAD

**Issue by VortiK** [Pandemoneus/Resource-Labels#12]
Hello, 

Thanks for adding support to my mod in yours !

I was taking a look at the code and found a little error, the uranium ore icon will not work, it is missing "-chunk" at the end of the icon filename.

https://github.com/Pandemoneus/Resource-Labels/blob/5caf7b3b2431cb5eed417738c7820a804d37a6db/config.lua#L87

Regards

**Comment by Pandemoneus** [comment]
Fixed in 0.16.6.
