### ISSUE TITLE
Deep Core Mining Support

### ISSUE THREAD

**Issue by jarquafelmu** [Pandemoneus/Resource-Labels#13]
Loving your mod. I always label resources and I am so grateful that your mod does this automatically for me.

Would you please consider adding support for [Deep Core Mining](https://mods.factorio.com/mod/vtk-deep-core-mining)? The entity being reported is `vtk-deepcore-mining-crack` from that mod..

Thanks!

**Comment by Pandemoneus** [comment]
I already added support, but he's pushing so many updates with new resources at the moment that I would have to update quite often too.
Going to do this now, and add an option to disable the "unknown resource entity" message.

**Comment by Pandemoneus** [comment]
Added in 0.16.7.
