### ISSUE TITLE
MadClown01's Extended AngelBob Minerals

### ISSUE THREAD

**Issue by MadClown01** [Pandemoneus/Resource-Labels#14]
Hello,
Several users of my mod have asked me to contact you in regards to adding support for my mod at https://forums.factorio.com/viewtopic.php?f=185&t=58136.

If that could be arranged that would be wonderful please.

Thanks,
MadClown01

**Comment by Pandemoneus** [comment]
Added in 0.16.8.

**Comment by MadClown01** [comment]
*heaps

**Comment by MadClown01** [comment]
Thanks heals
