### ISSUE TITLE
Add Alien Walls mod pls

### ISSUE THREAD

**Issue by flexoo** [Pandemoneus/Resource-Labels#3]
Could you please add this:

-- Alien Wall
addItem ("alien-biomass", "Alien Biomass", "alien-biomass")

It is from: https://mods.factorio.com/mods/vedrit/AlienWall

**Comment by Pandemoneus** [comment]
Added, you can now download the updated version on the mod portal.

**Comment by flexoo** [comment]
Thanks a lot for the quick add.
