### ISSUE TITLE
"attempt to compare nil with number" error

### ISSUE THREAD

**Issue by Tyler799** [Pandemoneus/Resource-Labels#4]
Factorio 0.16.5 (but also occured in 0.16.4, and possibly earlier)

Resource labels 0.16.1

When hitting Shift + G, I get the following error:

ResourceLabels/stdlib/area/area.lua:329: attempt to compare nil with number

It repeats several times, and then times out.

As well (likely due to this error) anything already labeled isn't un-labeled, and anything not labeled already doesn't become labeled. So shift+G doesn't do anything.

**Comment by Pandemoneus** [comment]
Do you play with other mods? Could you please post a mod list and upload the savegame when this happens? Thanks.

**Comment by Tyler799** [comment]
I should note, the mod worked fine at first in 0.16.x. It was only later on that it started to do this. (And I had RSO at the start, so I don't think that's it) 

Current Modlist:

- Explosive Termites
- Lighted Electric Poles
- Resource Spawner Overhaul
- Upgrade Builder And Planner
- Even Distribution
- AutoFill
- EvoGui
- Picker Extended
- Resource Labels
- Auto Research
- Honk
- Flow Control
- Bottleneck
- Auto Deconstruct
- Squeak Through
- FARL
- Robot Charging Station 1x1
- WaiTex (removed recently, causes crash on startup)

And here's my main save file:
[Main Save.zip](https://github.com/Pandemoneus/Resource-Labels/files/1582700/Main.Save.zip)

**Comment by Pandemoneus** [comment]
Alright, should be fixed in the new version 0.16.2. The problem was that you probably updated the mod in your play-through. I don't know why the data structures get invalidated after the update, so I am setting them up again, but that results in your old labels getting removed or them no longer being managed by the mod.
