### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by Lars8000** [Pandemoneus/Resource-Labels#5]
Please consider surporting resources in Factorio DrugLab

Mod page:
https://mods.factorio.com/mods/Shenpen/druglab

![coverage](https://user-images.githubusercontent.com/34163697/34335029-f32a9736-e94b-11e7-8b8b-9f39bdd8f141.png)
![manganesemining](https://user-images.githubusercontent.com/34163697/34335065-2db23ec2-e94c-11e7-8995-3362e484823b.png)

Kind regards
Lars Steffensen

**Comment by Pandemoneus** [comment]
Done and added in 0.16.3.

**Comment by Lars8000** [comment]
Much appreciated!
