### ISSUE TITLE
Unable to remove labels

### ISSUE THREAD

**Issue by Mr-Hick** [Pandemoneus/Resource-Labels#7]
I am unable to remove resource labels on the map.

Shift-h does not do anything.
If unchecked in the settings it will not mark the new patches but will still show data on the already marked ones.
Tried uninstalling but that does not remove the labels, 

Please help, there is way too much stuff on the map as it seams that there are hundreds of really small patches which cover the whole map and make it impossible to find anything.

Thank you
Ivica

**Comment by Pandemoneus** [comment]
If, for some reason, they bugged out, there is little I can do. I am saving which ones I created so I don't remove labels that other users created on their own. There are two ways you can remove your labels:
1. Right-click each label and delete them.
2. Run this command: `/c for _,tag in pairs(game.player.force.find_chart_tags(game.surfaces[1])) do tag.destroy() end`

**Comment by Mr-Hick** [comment]
The command worked, thank you.

It would be really nice if in the mod settings you could define minimum patch size to be marked,
this way it is just too many small patches in .16 that it makes the map unreadable.
